app/routes/auth.py
from flask import request, session, redirect, render_template
from flask import Blueprint, render_template
from flask import jsonify
from app.models.user import User
from app.services.user_service import UserService

# Blueprint llamado 'main'
auth_routes = Blueprint('auth_routes', __name__)

@auth_routes.route('/ingresar')
def login():
    return render_template('auth/login.html')

@auth_routes.route('/registrar')
def register():
    return render_template('auth/register.html')

@auth_routes.route("/login_user", methods=["POST"])
def login_user():
    if request.method == "POST":
        # Obtener los datos del formulario
        email = request.form["email"]
        password = request.form["password"]

        # Validar los datos del formulario
        user_service = UserService(email=email)
        user_service.validate_email()

        # Logear al usuario
        if User(email=email, password=password).login():
            # Si el login es exitoso
            return jsonify({"success": True, "message": "Inicio de sesión exitoso."})
        else:
            # Si el login falla
            return jsonify({"success": False, "message": "Contraseña o email incorrectos."})

@auth_routes.route("/register_user", methods=["POST"])
def register_user():
    if request.method == "POST":
        # Obtener los datos del formulario
        name = request.form["name"]
        lastname = request.form["lastname"]
        email = request.form["email"]
        password = request.form["password"]
        password_confirm = request.form["password_confirm"]

        # Validar los datos del formulario
        user_service = UserService(name=name, 
                                   lastname=lastname, 
                                   email=email, 
                                   password=password, 
                                   password_confirm=password_confirm)
        user_service.validate_all()

        # Registrar al usuario
        User(name=name, lastname=lastname, email=email, password=password).register()
        
        return redirect("/ingresar")  # Redirige al login después de registrar
    
    return render_template("register.html")  # Muestra el formulario si es GET

@auth_routes.route("/logout", methods=["POST"])
def logout():
    """Cierra la sesión del usuario."""
    session.pop("user_id", None)
    return redirect("/ingresar")

app/routes/finance_routes.py
from flask import Blueprint, session, redirect, render_template, request
from app.models.expenses import Expense
from app.models.user import User
from app.models.expense_category import ExpenseCategory
from app.models.expense_subcategory import ExpenseSubcategory

# Blueprint llamado 'main'
finance= Blueprint('finance', __name__)

@finance.route('/finanzas/presupuesto', methods=['GET'])
@finance.route('/finanzas/presupuesto/<string:category_name>', methods=['GET'])
def presupuesto(category_name=None):
    # Verificar si el usuario está logueado y obtener sus datos de sesión
    user_id = session.get("user_id")
    user_login_data = User(id=user_id).get_login_data()
    if not user_login_data:
        return redirect("/ingresar")
    
    # Obtener la familia seleccionada del usuario
    user_response = User(id=user_id).get_family_selected_id()
    family_id = user_response["family_selected_id"]

    # Obtener las categorías de egresos
    all_categories_response = ExpenseCategory(family_id=family_id).get_all_of_family()
    if not all_categories_response["success"]:
        return render_template('error.html', error=categories["error"])
    categories = all_categories_response["categories"]
    # Obtener el presupuesto total de la familia
    total_budget_response = ExpenseSubcategory().get_total_budget_by_family(family_id=family_id)
    if not total_budget_response["success"]:
        return render_template('error.html', error=total_budget_response["error"])
    total_budget = total_budget_response["total_budget"]

    subcategories = []
    selected_category = None
    if category_name:
        expense_category = ExpenseCategory(name=category_name)
        category_id_response = expense_category.get_id_by_name()
        if not category_id_response["success"]:
            return render_template('error.html', error=category_id_response["error"])
        selected_category = category_name
        category_id = category_id_response["id"]
    
        subcategories_response = ExpenseSubcategory(category_id=category_id).get_by_category_id()
        if not subcategories_response["success"]:
            return render_template('error.html', error=subcategories_response["error"])
        subcategories = subcategories_response["subcategories"]

    return render_template('presupuesto.html', user_login_data=user_login_data, categories=categories, subcategories=subcategories, selected_category=selected_category,
                           total_budget=total_budget)

@finance.route('/add_expense', methods=['POST'])
def add_expense():
    if request.method == 'POST':
        # Obtener los datos del formulario
        expense_date = request.form['expense_date']
        subcategory_id = int(request.form['subcategoria'])
        expense_amount = request.form['expense_amount']
        expense_description = request.form['expense_description']
        # Formatear datos recibidos
        format_amount = expense_amount.replace(".", "")
        # Obtener el ID del usuario de la sesión
        user_id = session.get("user_id")
        # Obtener la familia seleccionada del usuario
        user_response = User(id=user_id).get_family_selected_id()
        family_id = user_response["family_selected_id"]

        # Crear la instancia de Expense y guardar el gasto
        Expense(
            user_id=user_id,
            family_id=family_id,
            date=expense_date,
            subcategory_id=subcategory_id,
            amount=float(format_amount),
            description=expense_description
        ).create()
    
    return redirect('/finanzas')

@finance.route('/edit_expense', methods=['POST'])
def edit_expense():
    if request.method == 'POST':
        # Obtener los datos del formulario
        expense_id = request.form['edit_expense_id']
        expense_date = request.form['edit_expense_date']
        expense_subcategory = request.form['edit_subcategoria']
        expense_amount = request.form['edit_expense_amount']
        expense_description = request.form['edit_expense_description']
        # Formatear datos recibidos
        amount = expense_amount.replace(".", "")

        Expense(id=expense_id, date=expense_date, subcategory_id=expense_subcategory, 
                amount=amount, description=expense_description).edit()
        
        return redirect(f'/finanzas')

@finance.route('/delete_expense', methods=['POST'])
def delete_expense():
    if request.method == 'POST':
        # Obtener los datos del formulario
        expense_id = request.form['expense_id']

        Expense(id=expense_id).delete()
        
        return redirect(f'/finanzas')

app/routes/main.py
from flask import Blueprint, session, redirect, render_template, request
from app.models.family import Family
from app.models.user import User
from app.models.expense_category import ExpenseCategory

# Blueprint llamado 'main'
main = Blueprint('main', __name__)

@main.route('/')
def index():

    # Verificar si el usuario está logueado y obtener sus datos de sesión
    user_id = session.get("user_id")
    user_login_data = User(id=user_id).get_login_data()
    if not user_login_data:
        return render_template("index.html")

    # Obtener grupo familiar
    family_response = Family(id=user_id).get()
    families = family_response["families"] if family_response["success"] else []
    if not family_response["success"]:
        return render_template('error.html', error=family_response["error"])

    return render_template('index.html', user_login_data=user_login_data, families=families)

@main.route('/create_family', methods=['POST'])
def add_category():
    if request.method == 'POST':
        # Obtener los datos del formulario
        family_name = request.form['family_name']

        user_id = session.get("user_id")

        family = Family(name=family_name)
        created_family = family.create()
        print("Familia creada: ", created_family)
        if created_family["success"]:
            family.id = created_family["family_id"]
            #family.associate_with_user(user_id=user_id)
            print("Familia asociada al usuario: ", family.associate_with_user(user_id=user_id))
        else:
            return render_template('error.html', error=created_family["error"])
        
        return redirect('/')

@main.route('/finanzas')
def finanzas():

    # Verificar si el usuario está logueado y obtener sus datos de sesión
    user_id = session.get("user_id")
    user_login_data = User(id=user_id).get_login_data()
    if not user_login_data:
        return redirect("/ingresar")

    # Obtener las categorías de egresos
    all_categories_response = ExpenseCategory().get_select_data()
    if not all_categories_response["success"]:
        return render_template('error.html', error=all_categories_response["error"])
    categories = all_categories_response["categories"]

    return render_template('finanzas.html', user_login_data=user_login_data, categories=categories)

@main.route('/prestamos')
def prestamos():

    # Verificar si el usuario está logueado y obtener sus datos de sesión
    user_id = session.get("user_id")
    user_login_data = User(id=user_id).get_login_data()
    if not user_login_data:
        return redirect("/ingresar")

    return render_template('prestamos.html', user_login_data=user_login_data)

app/routes/main_routes.py
from flask import Blueprint, session, redirect, render_template, request
from app.models.family import Family
from app.models.user import User
from app.models.expenses import Expense
from app.models.expense_category import ExpenseCategory
from app.models.expense_subcategory import ExpenseSubcategory

# Blueprint llamado 'main'
main = Blueprint('main', __name__)

@main.route('/')
def index():

    # Verificar si el usuario está logueado y obtener sus datos de sesión
    user_id = session.get("user_id")
    user_login_data = User(id=user_id).get_login_data()
    if not user_login_data:
        return render_template("index.html")

    return render_template('index.html', user_login_data=user_login_data)

@main.route('/familias')
def familias():

    # Verificar si el usuario está logueado y obtener sus datos de sesión
    user_id = session.get("user_id")
    user_login_data = User(id=user_id).get_login_data()
    if not user_login_data:
        return redirect("/ingresar")
    
    # Obtener grupo familiar
    family_response = Family(id=user_id).get()
    families = family_response["families"] if family_response["success"] else []
    if not family_response["success"]:
        return render_template('error.html', error=family_response["error"])
    
    # Obtener la familia seleccionada por el usuario
    user_response = User(id=user_id).get_family_selected_id()
    family_selected_id = user_response["family_selected_id"]

    user_response = Family(id=family_selected_id).get_members()
    if not user_response["success"]:
        return render_template('error.html', error=user_response["error"])
    family_members = user_response["family_members"]

    family_response = Family(id=family_selected_id).get_roles()
    if not family_response["success"]:
        return render_template('error.html', error=family_response["error"])
    family_roles = family_response["family_roles"]

    return render_template('familias.html', user_login_data=user_login_data, families=families, family_members=family_members, 
                           family_selected_id=family_selected_id, family_roles=family_roles)

@main.route('/finanzas')
def finanzas():

    # Verificar si el usuario está logueado y obtener sus datos de sesión
    user_id = session.get("user_id")
    user_login_data = User(id=user_id).get_login_data()
    if not user_login_data:
        return redirect("/ingresar")
    
    # Obtener la familia seleccionada del usuario
    user_response = User(id=user_id).get_family_selected_id()
    family_id = user_response["family_selected_id"]

    # Obtener las categorías de egresos
    all_categories_response = ExpenseCategory(family_id=family_id).get_select_data()
    if not all_categories_response["success"]:
        return render_template('error.html', error=all_categories_response["error"])
    categories = all_categories_response["categories"]

    # Obtener el presupuesto total de la familia
    total_budget_response = ExpenseSubcategory().get_total_budget_by_family(family_id=family_id)
    if not total_budget_response["success"]:
        return render_template('error.html', error=total_budget_response["error"])
    total_budget = total_budget_response["total_budget"]
    if total_budget is None:
        total_budget = 0.0

    # Obtener el egreso total de la familia
    total_expense_response = Expense(family_id=family_id).get_total_expense_by_family()
    if not total_expense_response["success"]:
        return render_template('error.html', error=total_expense_response["error"])
    total_expense = total_expense_response["total_expense"]
    year = total_expense_response["year"]
    month = total_expense_response["month"]
    if total_expense is None:
        total_expense = 0.0

    # Obtener la diferencia entre el presupuesto y el gasto total
    difference = float(total_budget) - float(total_expense)


    # Obtener los egresos de la familia
    expenses_response = Expense(family_id=family_id).get_all_by_family()
    if not expenses_response["success"]:
        return render_template('error.html', error=expenses_response["error"])
    expenses = expenses_response["expenses"]

    return render_template('finanzas.html', user_login_data=user_login_data, categories=categories, total_budget=total_budget, 
                           expenses=expenses, total_expense=total_expense, difference=difference, year=year, month=month)

@main.route('/prestamos')
def prestamos():

    # Verificar si el usuario está logueado y obtener sus datos de sesión
    user_id = session.get("user_id")
    user_login_data = User(id=user_id).get_login_data()
    if not user_login_data:
        return redirect("/ingresar")

    return render_template('prestamos.html', user_login_data=user_login_data)

@main.route('/quehaceres')
def quehaceres():

    # Verificar si el usuario está logueado y obtener sus datos de sesión
    user_id = session.get("user_id")
    user_login_data = User(id=user_id).get_login_data()
    if not user_login_data:
        return redirect("/ingresar")

    return render_template('quehaceres.html', user_login_data=user_login_data)

app/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <!-- CSS globales-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/info-card.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/buttons.css') }}">
    <!-- CSS por página -->
    {% block css %}{% endblock %}

</head>

<body>
    <!-- Header de la página -->
     {% block header %}
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-sm fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Family administrator</a>
                <div style="display: flex; flex-direction: row; align-items: center; justify-content: center;">
                    {% if session.get('user_id') %}
                        <div style="display: flex; align-items: center; gap: 10px;">
                            <h5 style="margin: 0;">¡Hola!, {{ user_login_data['name'] }}</h5>
                            <form action="/logout" method="POST">
                                <button type="submit" style="width: 150px; padding: 5px; background-color: #f44336; color: white; border: none; cursor: pointer; border-radius: 5px;">
                                    Cerrar sesión
                                </button>
                            </form>
                        </div>
                    {% else %}
                        <a href="{{ url_for('auth_routes.login') }}" style="text-decoration: none; color: #007bff;">Ingresar</a>
                    {% endif %}

                </div>
            </div>
        </nav>

        <!-- Sidebar -->
        <nav class="sidebar">
            <h4 class="text-center">Menú</h4>
            <a href=""></a>
            <a href="{{ url_for('main.familias') }}"><i class="bi bi-house-door"></i> <span>Familias</span></a>
            <a href="{{ url_for('main.finanzas') }}"><i class="bi bi-graph-up-arrow"></i> <span>Finanzas</span></a>
            <a><i class="bi bi-clipboard-check"></i> <span>Tareas domésticas</span></a>
            <!-- <a href="{{ url_for('main.quehaceres') }}"><i class="bi bi-clipboard-check"></i> <span>Tareas domésticas</span></a> -->
            <a><i class="bi bi-credit-card"></i> <span>Préstamos</span></a>
            <!-- <a href="{{ url_for('main.prestamos') }}"><i class="bi bi-credit-card"></i> <span>Préstamos</span></a> -->
        </nav>
    </header>
    {% endblock %}

    <!-- Contenido principal -->
    <main>
        {% block content %}{% endblock %}
    </main>

    <!-- Footer de la página -->
    <footer>

    </footer>
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- SweetAlert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- JavaScript globales -->
    <script src="{{ url_for('static', filename='js/utils.js') }}"></script>
    <!-- JavaScript por página -->
    {% block js %}{% endblock %}
</body>

</html>

app/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Error</h1> 
</body>
</html>

app/templates/presupuesto.html
{% extends 'base.html' %}
{% block title %}Presupuesto{% endblock %}

<!-- Estilos css personalizados por página -->
{% block css %}
{% endblock %}

<!-- Contenido principal de la página -->
{% block content %}
<div class="container-fluid cont-main">
    <div class="row gx-0">
        <div class="col cont-top-directions">
            <h5 class="windows-name">Finanzas</h5>
            <a href="{{ url_for('main.index') }}" class="direction-name">Inicio</a>
            <i class="bi bi-chevron-right direction-icon"></i>
            <a href="{{ url_for('main.finanzas') }}" class="direction-name">Finanzas</a>
            <i class="bi bi-chevron-right direction-icon"></i>
            <p class="direction-select">Presupuesto</p>
        </div>
        <div class="col cont-top-buttons">
            <!-- Button to Open the Modal -->
            <button type="button" class="btn btn-blue" data-bs-toggle="modal" data-bs-target="#agregarCategoria">
                Agregar categoría
            </button>
        </div>
    </div>

    <div class="row gx-0">
        <!-- CARD 1 -->
        <div class="col">
            <div class="info-card">
                <p class="card-top-info">Presupuesto Total Mensual</p>
                <div class="data-and-percent">
                    {% if total_budget %}
                    <p class="card-data">${{ "{:,.0f}".format(total_budget) | replace(",", ".") }}</p>
                    {% else %}
                    <p class="card-data">$0</p>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
    <div class="row gx-0">
        <div class="col">
            <div>
                <h5 class="windows-name pb-4">Categorías</h2>
            </div>
            <div class="info-card">
                <style>
                    .cont-categorias {
                        width: 100%;
                        display: flex;
                        flex-direction: column;
                        gap: 20px;
                    }

                    .categoria {
                        display: flex;
                        flex-direction: row;
                        justify-content: space-between;
                        cursor: pointer;
                    }
                </style>
                <div class="cont-categorias">
                    {% for category in categories %}
                    <a class="info-card categoria clickable-card" href="{{ url_for('finance.presupuesto', category_name=category['name']) }}">
                        <p>{{ category['name'] }}</p>
                        {% if category['total_category_budget'] %}
                        <p>${{ "{:,.0f}".format(category['total_category_budget']) | replace(",", ".") }}</p>
                        {% else %}
                        <p>$0</p>
                        {% endif %}
                    </a>
                    {% endfor %}
                </div>

            </div>
        </div>
        <div class="col">
            {% if selected_category %}
            <div>
                <h5 class="windows-name pb-4">{{ selected_category }}</h5>
            </div>
            <div class="info-card">
                <!-- Tabbla con los datos y presupuestos por sub-categorías -->
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Presupuesto</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for subcategory in subcategories %}
                        <tr>
                            <td>{{ subcategory['name'] }}</td>
                            <td>${{ "{:,.0f}".format(subcategory['budget']) | replace(",", ".") }}</td>
                            <td style="width: 33.3%;">
                                <div class="cont-btns-acciones">
                                    <!-- Botón para cambiar el estado de la subcategoría -->
                                    <form action="/cambiar_estado_sub_categoria">
                                        <input type="hidden" name="category_name" value="{{ selected_category }}">
                                        <input type="hidden" name="subcategory_id" value="{{ subcategory['id'] }}">
                                        <button type="submit" class="bi bi-check-circle"
                                            style="color: var(--green); font-size: 20px; background: none; border: none; padding: 0; cursor: pointer;"
                                            title="Desactivar" disabled>
                                        </button>
                                    </form>
                                    <!-- Botón para editar la subcategoría -->
                                    <button type="button" class="bi bi-pencil-square"
                                        style="color: var(--blue); font-size: 20px; background: none; border: none; padding: 0; cursor: pointer;"
                                        data-bs-toggle="modal" data-bs-target="#editSubcategory"
                                        data-subcategory-id="{{ subcategory['id'] }}"
                                        data-subcategory-name="{{ subcategory['name'] }}"
                                        data-subcategory-budget="{{ subcategory['budget'] | replace('.', '') }}"
                                        title="Editar">
                                    </button>
                                    <!-- Botón para eliminar la subcategoría -->
                                    <form class="delete-form" action="/delete_subcategory" method="POST">
                                        <input type="hidden" name="category_name" value="{{ selected_category }}">
                                        <input type="hidden" name="subcategory_id" value="{{ subcategory['id'] }}">
                                        <button type="submit" class="bi bi-trash3"
                                            style="color: var(--red); font-size: 20px; background: none; border: none; padding: 0; cursor: pointer;"
                                            title="Eliminar">
                                        </button>
                                    </form>
                                </div>

                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="card-footer" style="height:auto; width: 100%">

                    <button class="btn btn-blue" data-bs-toggle="modal" data-bs-target="#subcategory">Agregar</button>

                    <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="javascript:void(0);">Previous</a></li>
                        <li class="page-item active"><a class="page-link" href="javascript:void(0);">1</a></li>
                        <li class="page-item"><a class="page-link" href="javascript:void(0);">Next</a></li>
                    </ul>
                </div>
            </div>
            {% else %}
            <div>
                <h5 class="windows-name pb-4">Selecciona una categoría</h5>
            </div>
            <div class="info-card">

            </div>
            {% endif %}
            
        </div>
    </div>
</div>

<!-- Modal para agregar una categoría -->
<div class="modal fade" id="agregarCategoria">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="egresoForm" action="/add_category" method="POST">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Agregar categoría</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>

                <!-- Modal Body -->
                <div class="modal-body">

                    <div class="cont-label-input">
                        <label for="category_name">Nombre categoría</label>
                        <input type="text" id="category_name" name="category_name" required>
                        <span class="error" id="montoError"></span>
                    </div>

                </div>

                <!-- Modal Footer -->
                <div class="modal-footer">
                    <button type="submit" class="btn btn-blue">Agregar</button>
                </div>
            </form>

            <style>
                .error {
                    color: red;
                    font-size: 0.875em;
                    display: block;
                    margin-top: 5px;
                }
            </style>

        </div>
    </div>
</div>
<!-- Modal para agregar una subcategoría -->
<div class="modal fade" id="subcategory">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="egresoForm" action="/add_subcategory" method="POST">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Agregar subcategoría</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>

                <!-- Modal Body -->
                <div class="modal-body">

                    <div class="cont-label-input">
                        <label for="subcategory_name">Nombre subcategoría</label>
                        <input type="text" id="subcategory_name" name="subcategory_name" required>
                        <span class="error" id="montoError"></span>
                    </div>
                    <div class="cont-label-input">
                        <label for="subcategory_budget">Presupuesto subcategoría</label>
                        <input type="text" id="subcategory_budget" name="subcategory_budget" oninput="formatMonto(this)" required>
                        <span class="error" id="montoError"></span>
                    </div>

                </div>

                <!-- Modal Footer -->
                <div class="modal-footer">
                    <input type="hidden" name="category_name" value="{{ selected_category }}">
                    <button type="submit" class="btn btn-blue">Agregar</button>
                </div>
            </form>

            <style>
                .error {
                    color: red;
                    font-size: 0.875em;
                    display: block;
                    margin-top: 5px;
                }
            </style>

        </div>
    </div>
</div>
<!-- Modal para editar una subcategoría -->
<div class="modal fade" id="editSubcategory">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="egresoForm" action="/edit_subcategory" method="POST">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Editar subcategoría</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>

                <!-- Modal Body -->
                <div class="modal-body">

                    <div class="cont-label-input">
                        <label for="edit_subcategory_name">Nombre subcategoría</label>
                        <input type="text" id="edit_subcategory_name" name="edit_subcategory_name" required>
                        <span class="error" id="montoError"></span>
                    </div>
                    <div class="cont-label-input">
                        <label for="edit_subcategory_budget">Presupuesto subcategoría</label>
                        <input type="text" id="edit_subcategory_budget" name="edit_subcategory_budget" oninput="formatMonto(this)" required>
                        <span class="error" id="montoError"></span>
                    </div>

                </div>

                <!-- Modal Footer -->
                <div class="modal-footer">
                    <input type="hidden" name="edit_subcategory_id" id="edit_subcategory_id">
                    <input type="hidden" name="category_name" value="{{ selected_category }}">
                    <button type="submit" class="btn btn-blue">Actualizar</button>
                </div>
            </form>

            <style>
                .error {
                    color: red;
                    font-size: 0.875em;
                    display: block;
                    margin-top: 5px;
                }
            </style>

        </div>
    </div>
</div>
{% endblock %}

<!-- JavaScript personalizado por página -->
{% block js %}
<script src="{{ url_for('static', filename='js/add-egreso-form.js') }}"></script>
<script src="{{ url_for('static', filename='js/swal/delete-form.js') }}"></script>
<script src="{{ url_for('static', filename='js/from-records-to-modals.js') }}"></script>
{% endblock %}